### ISSUE TITLE
Invalid JSON in body

### ISSUE THREAD

**Issue by DEV-XiA** [ddinchev/bokun-postman-pre-request#1]
Thank you for your work! 
I try to use postman to post Bokun API as you suggested but I got something wrong like:

**{
    "message": "Invalid JSON in body",
    "fields": {}
}**

I have added the "Content-Type": "application/json" in body but still got same wrong......

**Comment by ddinchev** [comment]
@DEV-XiA I'm glad that you found a solution (since you closed the issue). Would you tell what was the problem and how did you resolve it?
